variable "region" {}
variable "dynamo_db_table_name" {}
variable "dynamo_db_read_capacity" {}
variable "dynamo_db_write_capacity" {}
variable "dynamo_db_hash_key" {}
variable "dynamo_db_billing_mode" {}
variable "lambda_basic_policy" {}
variable "lambda_dynamodb_read_policy" {}
variable "role_name" {}
variable "lambda_dynamodb_put_policy" {}